os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py
  fast_finish: true

install: pip install -U tox

script: tox

cache: pip
