os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py
      script: tox
    - python: 3.5
      env: TOXENV=py
      script: tox
    - python: 3.6
      script: flake8 flask_meter
  fast_finish: true

install: pip install -U tox flake8

cache: pip
